version: '3'

services:

  logstash:
    build:
      context: ../../
      dockerfile: scripts/Dockerfile
      args:
        - LOGSTASH_VERSION=${LOGSTASH_VERSION:-8.3.2}
    command: /usr/share/plugins/plugin/scripts/unit-test/logstash-run.sh
    env_file: ../docker.env
    environment:
      - SPEC_OPTS
      - LOG_LEVEL # devutils (>= 2.0.4) reads the ENV and sets LS logging
    tty: true
